name: tongnyampah
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.2
  bottom_navy_bar: ^5.3.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.3
  firebase_storage: ^3.1.1
  flutter_screenutil: ^0.5.2
  image_picker: ^0.6.1+8
  intl: ">=0.14.0"
  flutter_html: ^0.11.0
  recase: ^3.0.0
  flutter_spinkit: ^4.1.2+1
  gradient_app_bar: ^0.1.3
  carousel_slider: ^2.2.1
  flutter_google_maps: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/images/logos/iconrwh.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/BG_bottom_create_acount.png
   - assets/images/BG_top_create_acount.png
   - assets/images/buang_sampah.png
   - assets/images/tukar_point.png
   - assets/images/daur_ulang.png
   - assets/images/laporkan.png
   - assets/images/first_page_image.png
   - assets/images/first_page_bottom.png
   - assets/images/daftar.png
   - assets/images/about-developer-pic.png
   #Logos Apps
   - assets/images/logos/icon.png
   - assets/images/logos/icon-white.png
   - assets/images/logos/icon-blue.png
   - assets/images/logos/icon-tosca.png
   - assets/images/logos/iconrbl.png
   - assets/images/logos/iconrwh.png
   - assets/images/logos/logo_typography.png
   - assets/images/logos/rounded_black.png
   - assets/images/logos/rounded_icon_wh.png
   - assets/images/logos/typo.png
   #Placholder Apps
   - assets/images/placeholders/Framegift.png
   - assets/images/placeholders/highlightgift.png
   - assets/images/placeholders/placeholder_iklan.png
   - assets/images/placeholders/artikel.png
   #Gamifications
   - assets/images/gamifications/bronze.png
   - assets/images/gamifications/silver.png
   - assets/images/gamifications/gold.png
   #Icons
   - assets/images/icons/google.png
   - assets/images/icons/google-blue.png
   - assets/images/icons/cupon.png
   - assets/images/icons/settings.png
   - assets/images/icons/share.png
   - assets/images/icons/code.png
   - assets/images/icons/log-out.png
   - assets/images/icons/edit-outline.png
   - assets/images/icons/syarat-ketentuan.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
